### ISSUE TITLE
[Bug] Focus Changes while pattern is still matching?

### ISSUE THREAD

**Issue by Udayraj123** [AliAzaz/Edittext-Library#1]
Hi, thanks for making this library, I've found it pretty useful. There is one issue I'm facing though - 
I'm using a pattern to take vehicle number plate as input. I've used the following xml for this.
```
<com.edittextpicker.aliazaz.EditTextPicker
    android:id="@+id/vehicle_number"
    ...
    app:defaultValue="null"
    app:pattern="[A-Z]{2}[0-9]{2}[A-Z]+[0-9]+"
    app:required="true"
    app:type="equal" />
```
And the corresponding java code is  : 
```
edittext.addTextChangedListener(new TextWatcher() {
        @Override
        public void onTextChanged(CharSequence arg0, int arg1, int arg2, int arg3) {
            if(edittext.isTextEqualToPattern()){
                    ...
            }
        }
        ...
});
```
There is another (android's) edit text present in the view. 
*The issue:* Text I want to enter in above field is "AB12CD1234". But the focus shifts to the other edit text as soon as I type "AB12CD1" (right when it matches the text for first time). This is an undesired behavior, I simply want to validate the text and not change the focus.
 
I'm fairly new to android, so can't say for sure, but I've checked your source and the bug seems to be around line 237 in `isTextEqualToPattern()` : 
```
    // call for checking default value in textbox
    public boolean isTextEqualToPattern() {            
            ...
        if (!checkingTextPattern())
            ...
        super.setError(null);
        super.clearFocus(); // <-- Is this required?
            ...
    }

    private boolean checkingTextPattern() {
         ...
        if (!super.getText().toString().matches(pattern)) {
            super.setFocusableInTouchMode(true);
            super.requestFocus();
            ...
        }
        ...
    }
```

**Comment by AliAzaz** [comment]
Thanks Udayraj for point out the issue. Let me check it and will update to you in a day.

**Comment by AliAzaz** [comment]
Udayraj, I fixed an issue and drafted new release.

**Comment by Udayraj123** [comment]
Sorry for the delay... I'm checking now.

**Comment by Udayraj123** [comment]
Yes. It doesn't change the focus now :smile: 
Now I noticed one more bug.. Even when the TextView's parent View is **invisible**, the hint text in red is still visible. Can you solve that issue as well here or shall I create a new one?

**Comment by AliAzaz** [comment]
Sorry for late reply. As, I was too busy in some other work.
I fixed that threat and drafted new release. 
You can also do your contribution in this library. Simply fork this repo, push your contribution and generate pull request. I would appreciate it.

**Comment by Udayraj123** [comment]
Okay. Now that you've fixed it I'm closing the issue.
I may as well contribute to this in the future :)
